kafkaHosts:
  - localhost:9092

jobs:
- name: BatchSmsEtl
  input: ./dataset/sms
  output: ./dataset/output/sms

- name: StreamingSmsEtl
  checkpoint: checkpoint/StreamingSmsEtl
  startingOffsets: latest
  input: sms-raw
  output: sms-enriched

- name: StreamingSmsWordCountEtl
  checkpoint: checkpoint/StreamingSmsWordCountEtl
  startingOffsets: latest
  input: sms-enriched
  output: ./dataset/output/wordCount